import type { UIDataTypes, UIMessage } from "ai";

export interface AgentTarget {
  id: string;
  description: string;
  /**
   * Opt-in for the interact tool: the model may click this element. The
   * element itself must also be a natively clickable control (button-like);
   * highlightable never implies clickable.
   */
  interactive?: boolean;
}

export interface AgentRoute {
  route: string;
  title: string;
  description: string;
  targets: AgentTarget[];
}

/** Generated by `agent-ui sync`. Safe to ship to the browser: no markdown bodies. */
export interface AgentPublicManifest {
  routes: AgentRoute[];
}

/** A contextual task displayed before a conversation begins. */
export interface AgentStarterPrompt {
  label: string;
  prompt: string;
}

/**
 * Which edge of the text selection the "Ask" popover attaches to. The chosen
 * side is honored as-is — the popover is only nudged back inside the viewport,
 * never flipped to the opposite edge.
 */
export type AgentSelectionSide = "top" | "bottom" | "left" | "right";

/** Consumer-owned appearance and timing for the page highlight overlay. */
export interface AgentHighlightOptions {
  durationMs?: number;
  padding?: number;
  borderColor?: string;
  borderWidth?: number;
  borderStyle?: "solid" | "dashed" | "dotted";
  backgroundColor?: string;
  ringColor?: string;
  borderRadius?: string;
}

export type ToolPolicy = "auto" | "confirm" | "disabled";

export interface AgentToolPolicies {
  navigate: ToolPolicy;
  highlight: ToolPolicy;
  interact: ToolPolicy;
}

export interface NavigateInput {
  route: string;
}

export interface HighlightInput {
  target: string;
}

export interface InteractInput {
  target: string;
}

export interface AgentToolOutput {
  ok: boolean;
  reason?: string;
  /**
   * The route a rejected target actually lives on. Set with
   * `target-on-another-route` so the model can navigate there and retry instead
   * of treating the page action as impossible.
   */
  expectedRoute?: string;
  /** True when the user clicked Allow on the approval card (vs. auto policy). */
  approvedByUser?: boolean;
}

export interface AgentTools {
  navigate: { input: NavigateInput; output: AgentToolOutput };
  highlight: { input: HighlightInput; output: AgentToolOutput };
  interact: { input: InteractInput; output: AgentToolOutput };
  [k: string]: { input: unknown; output: unknown };
}

export type AgentUIMessage = UIMessage<unknown, UIDataTypes, AgentTools>;

export type AgentVariant = "dock" | "sidebar" | "spotlight";

/** Surface finish shared by every shell: opaque (default) or backdrop-blur. */
export type AgentAppearance = "default" | "glass";
